prima: Remove redefinition of tpAniSirGlobal
Already defined in sirApi.h included by sme_Api.h.

/mnt/ssd/kernels/mido/CORE/BAP/src/btampFsm.c:101:31: warning: redefinition of typedef 'tpAniSirGlobal' is a C11 feature [-Wtypedef-redefinition]
typedef struct sAniSirGlobal *tpAniSirGlobal;
                              ^
/mnt/ssd/kernels/mido/CORE/MAC/inc/sirApi.h:47:31: note: previous definition is here
typedef struct sAniSirGlobal *tpAniSirGlobal;
                              ^

Signed-off-by: Albert I <kras@raphielgang.org>
(cherry picked from commit c7d362c5e7b23c4074da7ba3675ce38e0c011251)
Signed-off-by: GeoPD <geoemmanuelpd2001@gmail.com>